name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: Whether to execute cache step

      node-version:
        type: choice
        options:
          - 22.x
          - 23.x
          - 24.x
        default: 24.x

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{inputs.node-version}}

      - name: Download cached dependencies
        id: cache
        if: inputs.use-cache
        uses: actions/cache@v3
        with:
          key: deps-node-modules-${{ hashFiles('04-using-actions/react-app/package-lock.json') }}
          path: 04-using-actions/react-app/node_modules

      - name: Install dependencies
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci

      - name: Run test
        run: npm run test

      - name: Building
        run: npm run build

      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"
