name: 15 - Working with Matrices

on: workflow_dispatch

jobs:
  backwards-compatibility:
    if: false
    runs-on: ${{matrix.os}}
    name: ${{matrix.os}}-${{matrix.node-version}}
    strategy:
      fail-fast: true # Setting fail-fast to false prevents GitHub from canceling all in-progress jobs if any matrix job fails. Default: true
      matrix:
        node-version: [22.x, 23.x, 24.x]
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - node-version: 21.x
            os: ubuntu-latest

          - os: ubuntu-latest
            node-version: 23.x
            tag: experimental

    steps:
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node-version}}

      - name: Fail if experimental
        if: matrix.tag == 'experimental'
        run: exit 1

      - name: Perform some tests
        run: |
          echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node-version}}"
          sleep 10

      - name: Upload test results
        run: echo "Uploading tests results"

  include-example:
    runs-on: ubuntu-latest
    name: ${{matrix.color}}-${{matrix.size}}-${{matrix.shape}}-${{matrix.opacity}}
    strategy:
      matrix:
        color: [red, green]
        shape: [circle, square]
        size: [small, large]

        include:
          - opacity: 50

          - color: red
            opacity: 75

          - shape: circle
            opacity: 100

          - color: red
            shape: triangle

          - color: green
            shape: circle
            size: medium

        exclude:
          - color: green
            shape: circle
    steps:
      - name: Dummy step
        run: echo "${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}--${{matrix.opacity}}"
